<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Controls\ConnectingSettingsControl.resx" />
    <EmbeddedResource Include="Controls\DBModelComplexEditor.resx" />
    <EmbeddedResource Include="Controls\DBModelListView.resx" />
    <EmbeddedResource Include="Controls\DBModelSelectedNewObject.resx" />
    <EmbeddedResource Include="Controls\DBModelSelectedList.resx" />
    <EmbeddedResource Include="Controls\DBModelPicker.resx" />
    <EmbeddedResource Include="Properties\Resources.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.5.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NpgDataBase\DataBaseProvaider\DataBaseProvaider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\DBModelComplexEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DBModelSelectedNewObject.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\DBModelSelectedList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
